[[Rusticl]]
arch = "x86_64"
git-tree-sha1 = "19b2b64e97d2193a80acad46349e025e94202e61"
libc = "glibc"
os = "linux"

    [[Rusticl.download]]
    sha256 = "76786d21002e2069b0cc56219cec4d14afc1652a1f72d83f3daa1a5a0fd5293a"
    url = "https://github.com/maleadt/Rusticl_jll.jl/releases/download/Rusticl-v25.2.0+0/Rusticl.v25.2.0.x86_64-linux-gnu.tar.gz"
[[Rusticl]]
arch = "aarch64"
git-tree-sha1 = "79c587ca3d2daa5974ca467288b8896c506fefc8"
libc = "glibc"
os = "linux"

    [[Rusticl.download]]
    sha256 = "f5b4ebf92ccfdcdd08932f634a7ee8bcb70408ba41dc1397e3558fd6de444ddf"
    url = "https://github.com/maleadt/Rusticl_jll.jl/releases/download/Rusticl-v25.2.0+1/Rusticl.v25.2.0.aarch64-linux-gnu.tar.gz"
