# Autogenerated wrapper script for Rusticl_jll for aarch64-linux-gnu
export libRusticlOpenCL

using SPIRV_Tools_jll
using libdrm_jll
using OpenCL_jll
JLLWrappers.@generate_wrapper_header("Rusticl")
JLLWrappers.@declare_library_product(libRusticlOpenCL, "libRusticlOpenCL.so.1")
function __init__()
    JLLWrappers.@generate_init_header(SPIRV_Tools_jll, libdrm_jll, OpenCL_jll)
    JLLWrappers.@init_library_product(
        libRusticlOpenCL,
        "lib/libRusticlOpenCL.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
        # Register this driver with OpenCL_jll
    if OpenCL_jll.is_available()
        push!(OpenCL_jll.drivers, libRusticlOpenCL)
    end

end  # __init__()
